spring:
  cloud:
    zookeeper:
      connect-string: localhost:2181
  application:
    name: user
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5434/user?user=app&password=pass}
  jpa:
    generate-ddl: true
    open-in-view: false
server:
  port: 0